# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecc1059fee088ffc13e3bfbae82fb2432c2de190373428113377683fa60ed9ccae515886f17e9d7a9896a292266bedba2faee03ab1d450661b37e7face918e34

test:
  secret_key_base: 9628b48ca19b956226a4878f4b8c7a75b2449c16781826942390629d66d1224ed11388985f7595268a9452ed1bdaa2f011866f40c7ab27b89123ca4348cd9701

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
